backend:
  name: git-gateway
  branch: main

media_folder: "obrazky/aktuality"
public_folder: "/obrazky/aktuality"

collections:
  - name: "aktuality"
    label: "Aktuality"
    folder: "data/aktuality"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Nadpis", name: "title", widget: "string"}
      - {label: "Datum", name: "date", widget: "datetime"}
      - {label: "Náhledový obrázek", name: "thumbnail", widget: "image", required: false}
      - {label: "Text aktuality", name: "body", widget: "markdown"}
